// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7QGmXKn1uEPhuSQRYYoCv1vdQ7KlnJmM',
    appId: '1:943226169274:web:bf33543d4a58d369bcdf83',
    messagingSenderId: '943226169274',
    projectId: 'ticket-concert-e9647',
    authDomain: 'ticket-concert-e9647.firebaseapp.com',
    storageBucket: 'ticket-concert-e9647.firebasestorage.app',
    measurementId: 'G-EGP7EEFEVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWrx-CIsIfNW-dSkiBtHV6V9TvSN4lM78',
    appId: '1:943226169274:android:2f02e1b23fe806a8bcdf83',
    messagingSenderId: '943226169274',
    projectId: 'ticket-concert-e9647',
    storageBucket: 'ticket-concert-e9647.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7QGmXKn1uEPhuSQRYYoCv1vdQ7KlnJmM',
    appId: '1:943226169274:web:643938a8de2494dbbcdf83',
    messagingSenderId: '943226169274',
    projectId: 'ticket-concert-e9647',
    authDomain: 'ticket-concert-e9647.firebaseapp.com',
    storageBucket: 'ticket-concert-e9647.firebasestorage.app',
    measurementId: 'G-F548ERNEMX',
  );
}
